spring:
  security:
    user:
      name: jakub
      password: 123

  jpa:

    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:33527/data_db?user=jakub&password=pass
    driver-class-name: org.postgresql.Driver
  lifecycle:
    timeout-per-shutdown-phase: 1m
  flyway:
    user: jakub
    password: pass
    schemas: data_db



server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

bearer-token: b-token
api-token: api-token

jwt:
  secret: d39f61435f803dc554b3f61620684c5141d354fbe3072ad69a85858a8b60daec



