spring:
#  security:
#    user:
#      name: jakub
#      password: 123

  lifecycle:
    timeout-per-shutdown-phase: 1m

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

bearer-token: b-token



