spring:
  security:
    user:
      name: jakub
      password: 123


  datasource:
    hikari:
#      username: jakub
#      password: pass
      jdbc-url: jdbc:postgresql://localhost:5432/data_db?user=jakub&password=pass
    driver-class-name: org.postgresql.Driver





  lifecycle:
    timeout-per-shutdown-phase: 1m

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

bearer-token: b-token
api-token: api-token
jwt:
  secret: d39f61435f803dc554b3f61620684c5141d354fbe3072ad69a85858a8b60daec



