server:
  shutdown: graceful
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

spring:
  security:
    user:
      name: jakub
      password: 123
      roles: test

  lifecycle:
    timeout-per-shutdown-phase: 1m
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/data_db
    username: jakub
    password: pass

bearer-token: b-token
api-token: api-token

jwt:
  secret: d39f61435f803dc554b3f61620684c5141d354fbe3072ad69a85858a8b60daec







#
#message: "test message"

