server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m






#
#message: "test message"

