server:
  shutdown: graceful
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

spring:
  security:
    user:
      name: jakub
      password: 123
      roles: test

  lifecycle:
    timeout-per-shutdown-phase: 1m

bearer-token: b-token
api-token: api-token







#
#message: "test message"

