apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux
  namespace: default
spec:
  selector:
    matchLabels:
      run: webflux
  template:
    metadata:
      labels:
        run: webflux
    spec:
      containers:
        - image: japca/webflux:1.11
          imagePullPolicy: IfNotPresent
          name: webflux
          ports:
            - containerPort: 8081
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: webflux
  namespace: default
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"

spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    run: webflux
  type: NodePort
  externalIPs:
    - 70.34.245.253